import { chromium } from '/Users/Prequel/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/index.mjs';
const exe = '/Users/Prequel/Library/Caches/ms-playwright/chromium_headless_shell-1217/chrome-headless-shell-mac-arm64/chrome-headless-shell';
const b = await chromium.launch({ executablePath: exe });
const p = await b.newPage();
let api = [];
p.on('response', r => { if (r.url().includes('api/v1/form')) api.push(r.status()); });
await p.goto('https://oriole-nursery---new.webflow.io/summer-registration', { waitUntil: 'networkidle', timeout: 60000 });
await p.waitForTimeout(2500);
const opts = await p.evaluate(() => [...document.querySelectorAll('select')].map(s => s.name + ':' + s.options.length).join(', '));
console.log('selects:', opts);
await p.click('.on15-wk');
await p.waitForTimeout(300);
await p.fill('input[name="Child First Name"]', 'QA');
await p.fill('input[name="Child Last Name"]', 'CampTest');
await p.fill('input[name="Home Address"]', '123 Test St, Toronto');
await p.fill('input[name="Parent 1 Name"]', 'QA Parent');
await p.fill('input[name="Parent 1 Phone"]', '4165551234');
await p.fill('input[name="Parent 1 Email"]', 'qa-test@example.com');
await p.fill('input[name="Parent 2 Name"]', 'N/A');
await p.fill('input[name="Parent 2 Phone"]', 'N/A');
await p.fill('input[name="Parent 2 Email"]', 'N/A');
await p.click('form[data-name="Camp Family Registration"] input[type="submit"]');
await p.waitForTimeout(4000);
const done = await p.evaluate(() => getComputedStyle(document.querySelector('.on15-f1 .w-form-done')).display);
console.log('family reg: api=' + api.join(',') + ' done=' + done);
// consent form e2e
await p.fill('form[data-name="Camp Consent and Waiver"] input[name="Child Full Name"]', 'QA CampTest');
await p.fill('input[name="Signature"]', 'QA Parent');
await p.evaluate(() => document.querySelector('input[name="Agree to Policies"]').click());
await p.click('form[data-name="Camp Consent and Waiver"] input[type="submit"]');
await p.waitForTimeout(4000);
const done2 = await p.evaluate(() => getComputedStyle(document.querySelector('.on15-f3 .w-form-done')).display);
console.log('consent: api=' + api.join(',') + ' done2=' + done2);
await b.close();
